version: '3.8'

services:
  pentest-multitools:
    build: .
    container_name: pentest-multitools
    image: pentest-multitools:latest
    
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
    
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    cap_add:
      - NET_ADMIN
      - NET_RAW
    
    ports:
      - "8080:8080"
    
    restart: unless-stopped
    
    stdin_open: true
    tty: true